# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.7

EAPI=8

CRATES="
	autocfg@1.1.0
	bindgen@0.61.0
	bitflags@1.3.2
	cc@1.0.79
	cexpr@0.6.0
	cfg-if@1.0.0
	clang-sys@1.6.0
	cmake@0.1.49
	either@1.8.1
	foreign-types-macros@0.2.2
	foreign-types-shared@0.3.1
	foreign-types@0.5.0
	glob@0.3.1
	indoc@1.0.9
	lazy_static@1.4.0
	lazycell@1.3.0
	libc@0.2.142
	libloading@0.7.4
	lock_api@0.4.9
	log@0.4.17
	memchr@2.5.0
	memoffset@0.6.5
	minimal-lexical@0.2.1
	nom@7.1.3
	once_cell@1.17.1
	parking_lot@0.12.1
	parking_lot_core@0.9.7
	peeking_take_while@0.1.2
	proc-macro2@1.0.51
	pyo3-build-config@0.17.3
	pyo3-ffi@0.17.3
	pyo3-macros-backend@0.17.3
	pyo3-macros@0.17.3
	pyo3@0.17.3
	quote@1.0.23
	redox_syscall@0.2.16
	regex-syntax@0.6.28
	regex@1.7.1
	rustc-hash@1.1.0
	scopeguard@1.1.0
	shlex@1.1.0
	smallvec@1.10.0
	syn@1.0.107
	target-lexicon@0.12.6
	thiserror-impl@1.0.38
	thiserror@1.0.38
	unicode-ident@1.0.6
	unindent@0.1.11
	which@4.4.0
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.45.0
	windows-targets@0.42.1
	windows_aarch64_gnullvm@0.42.1
	windows_aarch64_msvc@0.42.1
	windows_i686_gnu@0.42.1
	windows_i686_msvc@0.42.1
	windows_x86_64_gnu@0.42.1
	windows_x86_64_gnullvm@0.42.1
	windows_x86_64_msvc@0.42.1
"

DISTUTILS_USE_PEP517=maturin
DISTUTILS_EXT=1
PYTHON_COMPAT=( python3_{10..12} )
# TODO: retry pypi after 0.2.2, see https://github.com/vlaci/pyperscan/issues/23#issuecomment-1557354555.
inherit cargo distutils-r1

DESCRIPTION="Opinionated Python binding for Hyperscan focusing on easy of use and safety"
HOMEPAGE="
	https://vlaci.github.io/pyperscan/
	https://github.com/vlaci/pyperscan
	https://pypi.org/project/pyperscan/
"
SRC_URI="
	https://github.com/vlaci/pyperscan/archive/refs/tags/v${PV}.tar.gz -> ${P}.gh.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( MIT Apache-2.0 )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD ISC MIT
	Unicode-DFS-2016
"
SLOT="0"
KEYWORDS="~amd64"

# We may want to package the more portable vectorscan fork of hyperscan at
# some point. Also, >=5 is preferred for more features.
RDEPEND=">=dev-libs/hyperscan-5"
DEPEND="${RDEPEND}"

QA_FLAGS_IGNORED="usr/lib.*/py.*/site-packages/pyperscan/pyperscan.*"

DISTUTILS_ARGS=(
	--no-default-features
)

distutils_enable_tests pytest
